# Used in gate.yaml as secrets.yaml  (example: password: !secret gateesp_ota_password)
# Copy this file to your ESPHome folder as secrets.yaml (or append to it) and update all values.

gateesp_wifi_ssid: "WiFi SSID"
gateesp_wifi_password: "WiFi Password"
gateesp_encryption_key: "vQ0I7EfC25fTju/41LnKJQFG5DFLZR9m3ggWvfz7eiA=" # 32-byte base64 string - generate here: https://esphome.io/components/api.html
gateesp_ota_password: "1b4f64be2c81cd424617d1722962f50a" # MD5 hash of any password string (32 characters) - generate here: https://www.md5hashgenerator.com/
gateesp_web_user: "growboxguy"
gateesp_web_password: "gbox420"
